### ISSUE TITLE
Cannot find module 'Matter' in version 0.1.6

### ISSUE THREAD

**Issue by And-re** [dxu/matter-collision-events#2]
I just updated this package to version 0.1.6 in my project and I get this error:
```sh
[Error] Error: Cannot find module 'Matter'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at n (/Users/and_re/Projects/hax/node_modules/matter-collision-events/build/matter-collision-events.min.js:1:83)
    at Object.<anonymous> (/Users/and_re/Projects/hax/node_modules/matter-collision-events/build/matter-collision-events.min.js:1:273)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/and_re/Projects/hax/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
```
Everything works fine with 0.1.5 so I think it's because of this commit: https://github.com/dxu/matter-collision-events/commit/53c2d2471341d26616c3c3918f6740eed558e42a

**Comment by dxu** [comment]
hey @And-re, really sorry about that. I've updated the externals config and rebuilt it, if you update to 0.1.7, your issue should be resolved. 

Closing, but please reopen or let me know if you continue to experience the issue!

**Comment by And-re** [comment]
@dxu Thank you. It seems to work. Maybe you should also update this line with a new version https://github.com/dxu/matter-collision-events/blob/master/src/entry.js#L4 because still seeing the old version number is a little bit confusing:
![screen shot 2017-05-14 at 09 54 53](https://cloud.githubusercontent.com/assets/328414/26032125/72757154-388b-11e7-8d9c-8f652325a2f2.png)

**Comment by dxu** [comment]
Sigh, yeah you're right. I forgot that matter plugins have their own versions that they're reading off of. Thanks for the reminder, i'll bump it with the next version.

**Comment by And-re** [comment]
@dxu Ok, no problem. At least everything seems to work.
Do you think that adding a way to disable one of the callbacks temporary (e.g. onCollide) is useful?
